services:

  db:
    image: postgres:17.0-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: gamestackr_backend
      POSTGRES_USER: gamestackr_backend
      POSTGRES_PASSWORD: gamestackr_backend
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
    driver: local
