name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.11-buster

    services:
      db:
        image: postgres:17.0-alpine
        env:
          POSTGRES_DB: gamestackr_backend
          POSTGRES_USER: gamestackr_backend
          POSTGRES_PASSWORD: gamestackr_backend

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Git
        run: apt-get update && apt-get install -y git

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.8.4

      - name: Install Dependencies
        run: make install && make install-pre-commit

      - name: Lint
        run: make lint

      - name: Test
        run: make test
        env:
          GAMESTACKR_SETTING_DATABASES: '{"default":{"HOST":"db"}}'
          GAMESTACKR_SETTING_LOCAL_SETTINGS_PATH: './gamestackr/core/settings/templates/settings.github.py'
