name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.11-buster

    services:
      db:
        image: postgres:17.0-alpine
        env:
          POSTGRES_DB: gamestackr_backend
          POSTGRES_USER: gamestackr_backend
          POSTGRES_PASSWORD: gamestackr_backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.8.4

      - name: Cache pre-commit hooks
        uses: actions/cache@v2
        with:
            path: ~/.cache/pre-commit
            key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install Dependencies
        run: make install && make install-pre-commit

      - name: Lint
        run: make lint

      - name: Test
        run: make test
        env:
          GAMESTACKR_SETTING_DATABASES: '{"default":{"HOST":"db"}}'
          GAMESTACKR_SETTING_LOCAL_SETTINGS_PATH: './gamestackr/core/settings/templates/settings.github.py'
