name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.11

    services:
      db:
        image: postgres:17.0-alpine
        env:
          POSTGRES_DB: gamestackr_backend
          POSTGRES_USER: gamestackr_backend
          POSTGRES_PASSWORD: gamestackr_backend

    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
          poetry-version: 1.8.4

      - name: Install Dependencies
        run: make install && make install-pre-commit

      - name: Lint
        run: make lint

      - name: Test
        run: make test
        env:
          GAMESTACKR_SETTING_DATABASES: '{"default":{"HOST":"db"}}'
          GAMESTACKR_SETTING_LOCAL_SETTINGS_PATH: './gamestackr/core/settings/templates/settings.github.py'
